### PR TITLE
Ventilator marketplace

### PR DESCRIPTION
**Pull request by vlitvak**
I'd like to propose a ventilation-Uber that could be used to map the existing capacity and optimise its use (like move it between hospitals/countries) and in the future to optimise the use of new capacity that hopefully, the bright engineers here will generate.

### CODE REVIEW

**Comment by mazaira** [comment]
Hi @vlitvak , is this a work in progress document? How is it proposed the implementation?

**Comment by vlitvak** [comment]
This is just an idea at this stage. The implementation should be by building a website but the difficult bit is to create all the infrastructure behind it, like get the hospitals/governments to agree, build logistics etc.

**Comment by mazaira** [comment]
In order to accept it as a project proposal, could you be a bit more concrete regarding what should be implemented and how? Thanks :)

**Comment by mazaira** [comment]
Closing by lack of feedback. Please feel free to re-open if there would be any changes from the current state.

**Pull request closed without merging**
