### PR TITLE
docs(proposals): remove duplicated proposal

### PR DESCRIPTION
**Pull request by comoser**
- remove this proposal `web_app_resource_management.md` from Pedro Filipe in favor of the neighbourhood assistance app `neighbourhood_assistance.md`, that will have this feature on the Roadmap

### CODE REVIEW

**Comment by s0** [comment]
As discussed in slack (https://helpfulengineering.slack.com/archives/C010313P4A3/p1584408970088500), a few of us believe that these projects serve different goals, and so shouldn't be merged.

Namely, that `web_app_resource_management.md` is probably a useful tool for e.g. hospitals, orgs like red cross, local governments etc... to coordinate logistics around resources, whereas `neighbourhood_assistance.md` is about getting resources to individuals in quarantine.

They could potentially be eventually pulled in to the same app(s), or have some kind of integration, but they serve fundamentally different purposes.

**Comment by comoser** [comment]
> As discussed in slack (https://helpfulengineering.slack.com/archives/C010313P4A3/p1584408970088500), a few of us believe that these projects serve different goals, and so shouldn't be merged.
> 
> Namely, that `web_app_resource_management.md` is probably a useful tool for e.g. hospitals, orgs like red cross, local governments etc... to coordinate logistics around resources, whereas `neighbourhood_assistance.md` is about getting resources to individuals in quarantine.
> 
> They could potentially be eventually pulled in to the same app(s), or have some kind of integration, but they serve fundamentally different purposes.

I understand your point here, I put out this PR after talking with Pedro Filipe since this also came from him, and one of the goals in this proposal actually is the exact same as the neighborhood assistance app, but if we want to keep both I suggest we update this one, since it will definitely lead to confusion

**Review by puzzledbytheweb — COMMENTED** [review]
From the slack discussion - https://helpfulengineering.slack.com/archives/C010313P4A3/p1584408970088500

I am a bit unclear whether we should merge this is our proposal. @comoser, what do you think?

**Comment by comoser** [comment]
> From the slack discussion - https://helpfulengineering.slack.com/archives/C010313P4A3/p1584408970088500
> 
> I am a bit unclear whether we should merge this is our proposal. @comoser, what do you think?

My view on this is simple I guess. This proposal serves a similar purpose. My coven is this proposal stays here, is that it may overlap in the future with the neighborhood assistance app. From my point of view, a stock of material is something that may exist by itself, but then the proposal should clarify that the purpose should be to help hospitals and medical centers with critical materials, since general requests are going to be handled in the neighborhood assistance.

This doesn’t need to be in a roadmap for the assistance project, and maybe it doesn’t make sense to, but then this proposal should be refactored in order to give more value independently from the assistance project.

This is my take on this, and my opinion of course @puzzledbytheweb

**Comment by mazaira** [comment]
Hi everybody. 

I didn't dive in the matter of differences across projects, but If I could be at any help the matter: Pedro is both the author and the one requesting its deletion. Is that correct?

if @s0 or any other assumes the ownership of the proposal, it has its complete right to be kept. If on the other hand, the proposal has no owner, there is no value behind and could be removed. 

Does it sound legit?

**Comment by comoser** [comment]
> Hi everybody.
> 
> I didn't dive in the matter of differences across projects, but If I could be at any help the matter: Pedro is both the author and the one requesting its deletion. Is that correct?
> 
> if @s0 or any other assumes the ownership of the proposal, it has its complete right to be kept. If on the other hand, the proposal has now owner, there is no value behind and could be removed.
> 
> Does it sound legit?

It does make sense of course. I believe the ultimate unblocker here is really @puzzledbytheweb.

There are really 2 options here, we just need to be careful to not leave a proposal that may overlap with a project that is already gaining traction. It would be ungrateful to the people that would start to pick up the `web_app_resource_management.md` if at some point they realized that **part** of their project is being accomplished by another project. 

But I do think that with a bit of restructuring, that proposal could really be very useful. I just see it more as a hospital / medical facility mediator than to help people in need directly. That's just my vision

**Review by puzzledbytheweb — APPROVED** [review]
I was a bit off! This proposal `web_app_resource_management.md` should be removed! I thought we were talking about another proposal that I did not author.

Thanks and sorry for my misunderstanding

**Comment by comoser** [comment]
@mazaira can't actually merge this after it's been approved, so, can you please merge this?

**Comment by mazaira** [comment]
Let's give a bit of time to @s0 , as he might be in a different timezone. If there is no feedback I'll merge it.

**Comment by s0** [comment]
> I was a bit off! This proposal `web_app_resource_management.md` should be removed! I thought we were talking about another proposal that I did not author.
> 
> Thanks and sorry for my misunderstanding

In that case i'm happy for this proposal to be removed, and PR merged, I imagine that larger orgs like red cross, hospitals etc... already have an existing workflow for managing their own resources on a much larger scale... :)

**Review by s0 — APPROVED** [review]

**Review by mazaira — APPROVED** [review]

**Pull request merged**
