### PR TITLE
Propose artful_websites.md

### PR DESCRIPTION
**Pull request by BoraxTheClean**
Please let me know of any feedback on this proposal.

### CODE REVIEW

**Comment by hairychris** [comment]
Is this similar enough to https://github.com/Helpful-Engineers/resources/blob/master/software/proposals/advice_app.md to be worth combining and building a cross platform solution or is this more of a shareable meme info microsite?

**Comment by BoraxTheClean** [comment]
My vision is closer to a project that creates multiple: _shareable meme info microsite?_

I really like that phrasing @hairychris

**Review by hairychris — COMMENTED** [review]
can you please remove the blank lines at the beginning of the file and add a blank line after line 5 as this isn't valid Markdown

**Comment by BoraxTheClean** [comment]
Changes made, does this look good now?

**Review by hairychris — APPROVED** [review]

**Pull request merged**
