### PR TITLE
Create fundamentals.md & criteria directory

### PR DESCRIPTION
**Pull request by 2001kraft**
Selection criteria for the software projects, as-well as a file laying out fundamentals for said criteria were created.

### CODE REVIEW

**Review by mazaira — COMMENTED** [review]
Hi @2001kraft . I agree with the changes, would be worth to update the template accordingly?

**Review by helloanh — CHANGES_REQUESTED** [review]
This document is fine.  Please do not change the READMe.md

**Comment by helloanh** [comment]
Please update changes from master and keep README.md same as masters, then I'll merge

**Comment by 2001kraft** [comment]
> Please update changes from master and keep README.md same as masters, then I'll merge

There should no longer be any changes to the ReadMe.MD

**Pull request merged**
