### PR TITLE
Create Zero2: Self-monitoring app

### PR DESCRIPTION
**Pull request by dariodaprile**

### CODE REVIEW

**Comment by mazaira** [comment]
Hi @dariodaprile , would this be the same app than https://github.com/Helpful-Engineers/resources/pull/19/files ? If yes I already merged that one

**Comment by dariodaprile** [comment]
> Hi @dariodaprile , would this be the same app than https://github.com/Helpful-Engineers/resources/pull/19/files ? yes I already merged that one

@mazaira yes same app, I've asked @YoniSchirris some help because I wasn't sure you got it.

**Comment by mazaira** [comment]
Understood, in that case we could close the this PR right?

**Comment by YoniSchirris** [comment]
Yes, please

**Pull request closed without merging**
